---
  - name: Install spring boot application
    hosts: azure-hosts

    pre_tasks:
      - name: Install java
        apt:
          name: openjdk-21-jdk
          state: present
          update_cache: yes
        become: yes
        tags:
          - install
    
    tasks:
      - name: Debug appdir
        ansible.builtin.debug:
          msg: "appdir --> {{ansible_user_dir}}"

      - name: Ensure git is installed
        apt:
          name: git
          state: present
        become: yes
        tags:
          - install

      # Added ForwardAgent = yes to my config file,
      # in order for ssh-agent to have access to my keys remotely
      - name: Clone git repo
        git:
          repo: git@github.com:it2022057/ds-project-2024.git 
          dest: "{{ appdir }}"
          version: "{{ branch }}"
          accept_hostkey: yes
          force: yes

      - name: Populate application.properties
        lineinfile:
          dest: "{{ appdir }}/src/main/resources/application.properties"
          state: present
          regexp: "^{{item.key}}="
          line: "{{item.key}}={{item.value}}"
        with_items:
          - "{{app.env | dict2items}}"
        tags:
          - edit

        
      - name: Build spring project
        block:

          - name: Ensure mvnw is executable
            ansible.builtin.file:
              path: "{{ appdir }}/mvnw"
              mode: "0755"  # Gives execute permissions (rwxr-xr-x)
            tags:
              - edit

          - name: Build the Spring application
            command: "./mvnw package -Dmaven.test.skip "
            args:
              chdir: "{{ appdir }}"

      #      - name: "Run the Spring application"
      #        command: "java -jar target/springbootdemo-0.0.1-SNAPSHOT.jar"
      #        args:
      #            chdir: "{{ appdir }}"


        rescue:

          - name: Fetch the SHA-512 checksum for Maven 3.9.9
            get_url:
              url: https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip.sha512
              dest: /tmp/maven_sha512.txt
              validate_certs: yes
              force: yes

          - name: Read the SHA-512 checksum from the file
            command: cat /tmp/maven_sha512.txt
            register: sha512_checksum

          - name: Replace the distributionSha512Sum line in maven-wrapper.properties
            replace:
              path: "{{ appdir }}/.mvn/wrapper/maven-wrapper.properties"
              regexp: '^distributionSha'
              replace: "distributionSha512Sum={{ sha512_checksum.stdout }}"
            tags:
              - edit
            
          - name: Clean up the temporary file
            file:
              path: /tmp/maven_sha512.txt
              state: absent
            when: sha512_checksum is defined
            
        always:
          - name: Build the Spring application
            command: "./mvnw package -Dmaven.test.skip "
            args:
              chdir: "{{ appdir }}"


      - name: copy spring service file
        template:
          src: ../files/spring.service.j2
          dest: "/etc/systemd/system/spring.service"
        become: yes
        become_user: root
        notify: restart spring

      - name: reload spring service
        service:
          name: spring
          state: restarted
        become: yes

      - name: ensure spring service started
        service:
          name: spring
          state: started
          enabled: yes
        become: yes

      - name: APT - install nginx
        apt:
          name: nginx
          update_cache: yes
        become: yes
        tags:
          - install

      - name: Copy nginx conf file
        template:
          src: ../files/nginx.http.j2
          dest: "/etc/nginx/sites-available/spring"
        become: yes

      - name: enable spring site in nginx
        file:
          src: "/etc/nginx/sites-available/spring"
          dest: "/etc/nginx/sites-enabled/spring"
          state: link
        become: yes
        notify: restart nginx

      - name: de-activate default nginx site
        file:
          path: /etc/nginx/sites-enabled/default
          state: absent
        become: yes
        notify: restart nginx


    handlers:
      - name: restart spring
        service:
          name: spring
          state: restarted
        become: yes

      - name: restart nginx
        service:
          name: nginx
          state: restarted
        become: yes